version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
  pre_build:
    commands:
      - pnpm install
  build:
    commands:
      - pnpm run build
  post_build:
    commands:
      - cp package.json dist/
      - cp pnpm-lock.yaml dist/
      - cp Procfile dist/
      - cd dist && pnpm install --production
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'